# Generated by Django 6.0 on 2025-12-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('genres', models.JSONField(default=list)),
                ('num_episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('main_picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('entry_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimeEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='anime_compare.anime')),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='anime_compare.useranime')),
            ],
            options={
                'unique_together': {('user_list', 'anime')},
            },
        ),
    ]
